FROM ghcr.io/ledgerhq/speculos:sha-bced779

RUN apt update &&                                               \
    apt install -y curl jq build-essential libsodium-dev git xxd &&	\
    pip install base58 pytezos pytesseract &&                   \
    git clone --depth 1 --branch v1.11.4 https://github.com/ledgerHQ/ragger && \
    cd ragger &&                                                \
    pip install --extra-index-url https://test.pypi.org/simple/ '.[all_backends]' && \
    cd ..

ENV SPECULOS=/speculos/speculos.py
