FROM ghcr.io/ledgerhq/speculos:sha-744f56b

RUN apt update &&                                               \
    apt install -y curl jq build-essential libsodium-dev git &&	\
    pip install base58 pytezos &&                               \
    git clone --depth 1 --branch v1.11.1 https://github.com/ledgerHQ/ragger && \
    cd ragger &&                                                \
    pip install --extra-index-url https://test.pypi.org/simple/ '.[all_backends]' && \
    cd ..

ENV SPECULOS=/speculos/speculos.py
